### PR TITLE
docs: Add High Sierra mention

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Probably no reason to craft a new release for this, should work just on GitHub.

**Comment by wooorm** [comment]
too late; didn’t read!

**Comment by wooorm** [comment]
Meh, it’s fine 🤷‍♂️ Docs are important, and this thing doesn‘t get updated often, so it would mean that this “broken line” was in there for the foreseeable years!

**Comment by RichardLitt** [comment]
\o/ Super glad this works again, I was getting incredibly annoyed.

**Comment by wooorm** [comment]
I get that haha :p

Thanks so much for working on it Richard! 🎉

**Pull request merged**
